version: '3'

services:
  verification-bot:
    restart: always
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm run start"